"""Add is_deleted to Book

Revision ID: 160dffb5455b
Revises: 616f6d67429a
Create Date: 2025-04-11 13:36:49.916595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160dffb5455b'
down_revision = '616f6d67429a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_book_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_is_deleted'))
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
